version: '3.8'

services:
  pytask-manager:
    image: ghcr.io/yourusername/pytask-manager:latest
    ports:
      - "8000:8000"  # Backend + WebSocket + Static Files
    volumes:
      # Only map directories that need to persist data
      - ./data:/app/data        # SQLite database
      - ./scripts:/app/scripts  # User Python scripts
      - ./logs:/app/logs        # Execution logs
    # Optional: Environment variables (will use defaults if not set)
    environment:
      - PYTASK_DATABASE_URL=sqlite:///app/data/pytask.db
      - PYTASK_SCRIPTS_DIR=/app/scripts
      - PYTASK_LOGS_DIR=/app/logs
      # - PYTASK_DEBUG=false    # Uncomment to disable debug mode
      # - PYTASK_LOG_LEVEL=INFO # Uncomment to change log level
    restart: unless-stopped 