version: '3.8'

services:
  pytask-manager:
    image: ghcr.io/yourusername/pytask-manager:latest
    ports:
      - "8000:8000"  # Backend + WebSocket + Static Files
    volumes:
      - ./data:/app/data        # For database and other persistent data
      - ./scripts:/app/scripts  # For user scripts
      - ./logs:/app/logs        # For execution logs
    environment:
      - DATABASE_URL=sqlite:///app/data/pytask.db
      - SCRIPTS_DIR=/app/scripts
      - LOGS_DIR=/app/logs
    restart: unless-stopped 