name: Feature Request
description: Suggest an idea for PyTask-Manager
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form as completely as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: |
        Describe how you envision this feature working. Be as specific as possible.
        - What would the UI look like?
        - How would users interact with it?
        - What are the expected outcomes?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: |
        - Alternative 1: [...]
        - Alternative 2: [...]
        - Current workaround: [...]

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my use of the application)
        - High (Would significantly improve my workflow)
        - Medium (Would be nice to have)
        - Low (Just an idea)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of the application would this feature affect?
      multiple: true
      options:
        - Script Management
        - Dependency Management
        - Scheduling
        - Execution
        - Logging
        - User Interface
        - Security
        - Performance
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: |
        - Screenshots or mockups
        - Similar features in other applications
        - Technical considerations
        - Impact on existing features 