"""initial migration

Revision ID: 378ba4f11d45
Revises: 
Create Date: 2025-01-29 18:16:38.357604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '378ba4f11d45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if a table exists in the database."""
    inspector = Inspector.from_engine(op.get_bind())
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('scripts'):
        op.create_table('scripts',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('description', sa.String(length=1000), nullable=True),
            sa.Column('content', sa.String(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
        )

    if not table_exists('tags'):
        op.create_table('tags',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
        )

    if not table_exists('dependencies'):
        op.create_table('dependencies',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('script_id', sa.Integer(), nullable=False),
            sa.Column('package_name', sa.String(length=255), nullable=False),
            sa.Column('version_spec', sa.String(length=100), nullable=False),
            sa.Column('installed_version', sa.String(length=100), nullable=True),
            sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    if not table_exists('schedules'):
        op.create_table('schedules',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('script_id', sa.Integer(), nullable=False),
            sa.Column('cron_expression', sa.String(length=100), nullable=False),
            sa.Column('description', sa.String(length=255), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    if not table_exists('script_tags'):
        op.create_table('script_tags',
            sa.Column('script_id', sa.Integer(), nullable=True),
            sa.Column('tag_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
            sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
        )

    if not table_exists('executions'):
        op.create_table('executions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('script_id', sa.Integer(), nullable=False),
            sa.Column('schedule_id', sa.Integer(), nullable=True),
            sa.Column('started_at', sa.DateTime(), nullable=False),
            sa.Column('completed_at', sa.DateTime(), nullable=True),
            sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILURE', name='executionstatus'), nullable=False),
            sa.Column('log_output', sa.String(), nullable=True),
            sa.Column('error_message', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
            sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executions')
    op.drop_table('script_tags')
    op.drop_table('schedules')
    op.drop_table('dependencies')
    op.drop_table('tags')
    op.drop_table('scripts')
    # ### end Alembic commands ###
