name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'dev'
        type: choice
        options:
          - main
          - dev
  push:
    branches:
      - dev
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'migrations/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'run.py'
      - '.dockerignore'
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'migrations/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'run.py'
      - '.dockerignore'

env:
  REGISTRY: ghcr.io
  DEV_IMAGE_NAME: pytask-dev
  PROD_IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Only run if:
    # 1. It's a manual workflow dispatch
    # 2. It's a push to dev branch
    # 3. It's a merged PR to main branch
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/dev') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main' && github.head_ref == 'dev')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set image name based on event
        id: image_name
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.base_ref }}" == "main" ]]; then
            echo "IMAGE_NAME=${{ env.PROD_IMAGE_NAME }}" >> $GITHUB_ENV
            echo "Building production image for merged PR to main"
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "IMAGE_NAME=${{ env.DEV_IMAGE_NAME }}" >> $GITHUB_ENV
            echo "Building dev image for push to dev"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ github.event.inputs.branch }}" == "main" ]]; then
              echo "IMAGE_NAME=${{ env.PROD_IMAGE_NAME }}" >> $GITHUB_ENV
              echo "Building production image from workflow dispatch"
            else
              echo "IMAGE_NAME=${{ env.DEV_IMAGE_NAME }}" >> $GITHUB_ENV
              echo "Building dev image from workflow dispatch"
            fi
          fi

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Send Discord Notification
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DC_WEBHOOK }}
          DISCORD_USERNAME: "PyTask-Manager Build Bot"
          DISCORD_AVATAR: ${{ secrets.DC_ICON }}
        with:
          args: |
            🚀 **New Build Deployed Successfully!**
            
            Repository: `${{ github.repository }}`
            Branch: `${{ github.event.inputs.branch || github.ref_name }}`
            Commit: [`${{ github.sha }}`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            Image: `${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest`
            Type: `${{ env.IMAGE_NAME == env.DEV_IMAGE_NAME && 'Development' || 'Production' }}` 